import { v4 as uuid } from "uuid";
import { Images } from "../../Assets/Images/image";
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: "Rolled Oats | Gluten free | Lab Tested",
    price: 225,
    image: Images.oats,
    categoryName: "Healthy grains",
    ratings: 4,
    newItem: true,
    isOutOfStock: false,
  },
  {
    _id: uuid(),
    name: "Organic Cashew nuts (Kaju)",
    price: 400,
    image: Images.cashews,
    categoryName: "Nutritional Nuts",
    ratings: 4,
    isOutOfStock: false,
  },
  {
    _id: uuid(),
    name: "Organic Quinoa | (500g) | (Salvia hispanica)",
    price: 280,
    image: Images.quinoa,
    discount: true,
    priceBeforeDiscount: 400,
    discPerc: 30,
    categoryName: "Healthy grains",
    ratings: 3,
    sale: true,
    isOutOfStock: false,
  },
  {
    _id: uuid(),
    name: "Fresh | Organic Apples",
    price: 300,
    image: Images.apple,
    categoryName: "Fruits",
    ratings: 4,
    newItem: true,
    isOutOfStock: false,
  },
  {
    _id: uuid(),
    name: "Organic Chia Seeds",
    price: 250,
    image: Images.chiaSeeds,
    categoryName: "Super Seeds",
    ratings: 3,
    isOutOfStock: true,
  },
  {
    _id: uuid(),
    name: "Mixed Nuts | (500g)",
    price: 600,
    image: Images.mixedNuts,
    discount: true,
    priceBeforeDiscount: 750,
    discPerc: 20,
    categoryName: "Nutritional Nuts",
    ratings: 4,
    sale: true,
    isOutOfStock: false,
  },
  {
    _id: uuid(),
    name: "Fresh StrawBerries | (250g)",
    price: 390,
    image: Images.strawberries,
    categoryName: "Fruits",
    ratings: 3,
    isOutOfStock: false,
  },
  {
    _id: uuid(),
    name: "Organic Sunflower Seeds | (200g)",
    price: 100,
    image: Images.sunflowerSeeds,
    categoryName: "Super Seeds",
    ratings: 5,
    isOutOfStock: false,
  },
  {
    _id: uuid(),
    name: "Organic Flax Seeds | (200g)",
    price: 50,
    image: Images.flaxSeeds,
    categoryName: "Super Seeds",
    ratings: 5,
    isOutOfStock: false,
  },
  {
    _id: uuid(),
    name: "Fresh | Organic Mangoes | (1kg)",
    price: 120,
    image: Images.mangoes,
    categoryName: "Fruits",
    ratings: 3,
    isOutOfStock: false,
  },
  {
    _id: uuid(),
    name: "Farm fresh | Red Onions | (1kg)",
    price: 50,
    image: Images.onions,
    categoryName: "Vegetables",
    ratings: 4,
    isOutOfStock: false,
  },
  {
    _id: uuid(),
    name: "Farm fresh | Spinach | (250g)",
    price: 80,
    image: Images.spinach,
    categoryName: "Vegetables",
    ratings: 4,
    isOutOfStock: false,
  },
];
